version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - db_network
    restart: always

  koa-app:
    container_name: syluv-app
    build: .
    image: anjeonghoo/syluv-app
    environment:
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=syluvdatabase
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - redis
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
