spring:

  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://syluv-db.cb2sy0ccsa47.ap-northeast-2.rds.amazonaws.com:3306/syluv_db
    username: syluvdatabase
    password: syluvdatabase

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret: aGFuZXVtLWZvb2Rnby1qd3Qtc2VjcmV0LWtleQo=
    token:
      access-expiration-time: 86400000 #  24*60*60*1000 = 1일
      refresh-expiration-time: 604800000 # 7*24*60*60*1000 = 7일

logging:
  level:
    org:
      hibernate.sql: debug