spring:

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  h2-console:
    settings:
      web-allow-others: false

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
        show_sql: true

security:
  jwt:
    secret: aGFuZXVtLWZvb2Rnby1qd3Qtc2VjcmV0LWtleQo=
    token:
      access-expiration-time: 86400
      refresh-expiration-time: 86400

cors:
  allowed:
    origins: "*"

logging:
  level:
    org:
      hibernate.sql: debug
