spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  main:
    allow-bean-definition-overriding: true

---
spring:
  config:
    activate:
      on-profile: local
    import: application-local.yml, application-redis.yml, application-oauth.yml, application-s3.yml, application-payment.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: application-prod.yml, application-redis.yml, application-oauth.yml, application-s3.yml, application-payment.yml