spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      client:
        config:
          kakao-oidc-key-client:
            url: https://kauth.kakao.com

oauth:
  kakao:
    iss: https://kauth.kakao.com
    client-id: 6eb8b891882ab97eda313dfde621b743